mycard_main_homepage:
    path:     /
    defaults: { _controller: MycardMainBundle:Default:index }

mycard_main_usuario:
    path:     /
    defaults: { _controller: MycardMainBundle:Default:index }

