# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    providers:
        chain_provider:
          chain:
            providers: [sadm_security,user_security]
        sadm:
              name: sadm_security
              entity: {class: AppBundle:Administrador,
                       property: useAdm}
        user:
              name: user_security
              entity: {
                class: AppBundle:Usuario,
                property: username}
     
    firewalls:
        sadm:
            pattern: ^/sa
            anonymous: ~
            provider: sadm_security
            form_login:
                login_path: login
                check_path: login
                default_target_path: indexSAdmin
            logout:
                path:   /logout
                target: /
        user:
            pattern: ^/usuario
            anonymous: ~
            provider: user_security
            form_login:
                  login_path: login
                  check_path: login
                  default_target_path: /usuario
            logout:
                  path:   /logout
                  target: /

        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

    #    main:
     #      anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #form_login:
              # login_path: login
              #  check_path: login

            #logout:
             #   path:   /logout
              #  target: /

             #provider: db_provider

    access_control:
        #- {path: ^/[login|registrate], roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - {path: ^/usuario/login, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - {path: ^/sa/login, roles: IS_AUTHENTICATED_ANONYMOUSLY}
   #     - {path: ^/sa, roles: ROLE_SUPADMIN }
        - {path: ^/usuario, roles: ROLE_USER }
        #- { path: ^/, roles: IS_AUTHENTICATED_FULLY }
      
    encoders:
        #Esto sirve con los datos db_provider
        AppBundle\Entity\Usuario:
            algorithm: bcrypt
        #Esto sirve con los datos db_provider
        AppBundle\Entity\Administrador:
           algorithm: bcrypt
        #Esto son con los datos de in_memory
        Symfony\Component\Security\Core\User\User: 
             algorithm: bcrypt
             cost: 12