# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
    #chain_provider permite autenticacion tanto con datos in_memory como datos db_provider
        chain_provider:
            chain:
                providers: [sadmn_security, user_security]
        #in_memory:
        #    memory:
        #        users:
        #            admin:
        #              password: $2y$13$GdIw.hu0AVaCKc0B0LM2Ne43eVkFWbbl7riHAZMgaH.YBsffujW7O
        #              roles: 'ROLE_ADMIN' 
        #            sadmin:
        #              password: $2y$13$CT0aMemEO22bK3JC0PkmHOPKwsuFamNiGG92V5DKdYE3YiKxj/xxO 
        #              roles: 'ROLE_SUPADMIN'
        sadmn_security:
            entity:
                class: AppBundle:Administrador
                property: useAdm   
        user_security:
            entity:
                class: AppBundle:Usuario
                property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        sadm:
            anonymous: ~
            pattern: ^/sa
            provider: sadmn_security
            form_login:
                login_path: sadmnlogin
                check_path: sadmnlogin
                default_target_path: indexSAdmin
            logout:
                path:  sa_logout
                target: /     
        user:
            anonymous: ~
            pattern: ^/usuario
            provider: user_security
            form_login:
                login_path: login
                check_path: login
                default_target_path: user_index
            logout:
                path:   user_logout
                target: /
         
    access_control:
       - {path: ^/registrate, roles: IS_AUTHENTICATED_ANONYMOUSLY}
       - {path: ^/usuario/login, roles: IS_AUTHENTICATED_ANONYMOUSLY}
       - {path: ^/sa/login, roles: IS_AUTHENTICATED_ANONYMOUSLY}
       - {path: ^/sa, roles: ROLE_SUPADMIN }
       - {path: ^/usuario, roles: ROLE_USER }
       - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
    encoders:
        #Esto sirve con los datos db_provider
        AppBundle\Entity\Administrador:
           algorithm: bcrypt
        #Esto sirve con los datos db_provider
        AppBundle\Entity\Usuario:
            algorithm: bcrypt
        #Esto son con los datos de in_memory
        #Symfony\Component\Security\Core\User\User:
        #     algorithm: bcrypt
        #     cost: 12