# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        #in_memory:
        #   memory: 
        #         users:
        #             admin:
        #                 password: $2y$13$GdIw.hu0AVaCKc0B0LM2Ne43eVkFWbbl7riHAZMgaH.YBsffujW7O
        #                 roles: 'ROLE_ADMIN'
        #             sadmin:
        #                 password: $2y$13$CT0aMemEO22bK3JC0PkmHOPKwsuFamNiGG92V5DKdYE3YiKxj/xxO 
        #                 roles: 'ROLE_SUPADMIN'
        db_provider:
            entity:
                class: AppBundle:Usuario
                property: username 
                # remove this if you want to access using email or username
                # if you're using multiple entity managers
                # manager_name: customer

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            form_login:
                login_path: login
                check_path: login
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html    
            logout:
                path:   /logout
                target: /
            
            provider: db_provider
    access_control:
        - {path: ^/[login|registrate],roles:IS_AUTHENTICATED_ANONYMOUSLY}
        - {path: ^/usuario, roles: ROLE_USER }
      
    encoders:
        AppBundle\Entity\Usuario:
            algorithm: bcrypt
        # Symfony\Component\Security\Core\User\User: 
        #     algorithm: bcrypt
        #     cost: 12