administrador_index:
    path:     /
    defaults: { _controller: "AppBundle:Administrador:index" }
    methods:  GET

administrador_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Administrador:show" }
    methods:  GET

administrador_new:
    path:     /new
    defaults: { _controller: "AppBundle:Administrador:new" }
    methods:  [GET, POST]

administrador_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Administrador:edit" }
    methods:  [GET, POST]

administrador_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Administrador:delete" }
    methods:  DELETE
