pw_mc_main_homepage:
    path:     /
    defaults: { _controller: PwMCMainBundle:Default:index }

pw_mc_main_admin:
    path:     /sa/
    defaults: { _controller: PwMCMainBundle:SAdmin:index }

pw_mc_main_adminp:
    path:     /sa/{page}
    defaults: { _controller: PwMCMainBundle:SAdmin:pageselect,page:index }
    
pw_mc_main_catadd:
    path:     /categoria/addCat/{descripcion}
    defaults: { _controller: PwMCMainBundle:categorias:addCat,descripcion:ropa }

pw_mc_main_user:
    path:     /user/
    defaults: { _controller: PwMCMainBundle:User:index }

pw_mc_main_userp:
    path:     /user/{page}
    defaults: { _controller: PwMCMainBundle:User:pageselect,page:index }

pw_mc_main_userp:
    path:     /user/micard/
    defaults: { _controller: PwMCMainBundle:User:pageselect,page:index }